{% set name = "rainflow" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26b24f66dd8591dfd88566000a9b80a64a967e2ffa2825261b2b7db37aacd2da

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python

test:
  imports:
    - rainflow

about:
  home: https://github.com/iamlikeme/rainflow
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Implementation of ASTM E1049-85 rainflow cycle counting algorithm

  description: |
    rainflow is a Python implementation of the ASTM E1049-85 rainflow cycle counting algorithm for 
    fatigue analysis. No dependencies beside Python's standard library. Supports both Python 2 and 3.
  doc_url: https://github.com/iamlikeme/rainflow/
  dev_url: https://github.com/iamlikeme/rainflow/

extra:
  recipe-maintainers:
    - jfcorbett
